name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v5
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@v2
      - name: setup
        run: |
          luarocks install busted
      - name: test
        run: |
          busted -o utfTerminal
