name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck and stylua
        run: |
          apt-get update && apt-get upgrade -qq
          apt-get install luarocks -y
          luarocks install luacheck
      - name: Check style
        run: luacheck **/*.lua --codes
      - name: Check formats
        run: npx @johnnymorganz/stylua-bin -g '*.lua' --check  -- .
