name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install luacheck and stylua
        run: |
          npx @johnnymorganz/stylua-bin -y
          luarocks install luacheck
      - name: Check style
        run: luacheck **/*.lua --codes
      - name: Check formats
        run: stylua -g '*.lua' --check  -- .
